first version of GitHub Discussions rules - Closes #2
DevOpsItalia/devopsitalia.github.io pull request #6
Opened 2024-03-22 17:48 UTC by Kavuti

Nel file DISCUSSIONS_RULES.md è presente una prima bozza delle regole. Ogni parere è ben accetto.

2024-03-23 10:01 UTC, Mirio requested changes
A mio avviso includerei anche le parti del CoC "padre" al fine di avere una pagina che contiene tutte le "regole".
@DevOpsItalia/staffers che ne pensate?

2024-03-28 19:40 UTC, Kavuti commented
A quel punto non facciamo prima ad eleggere queste regole come generali senza distinguere tra CoC e regole?

2024-03-28 21:39 UTC, Mirio commented
> A quel punto non facciamo prima ad eleggere queste regole come generali senza distinguere tra CoC e regole?
Decisamente si, la mia idea era infatti "migrare" il link direttamente sulle nuove regole che stiamo facendo.

2024-04-03 08:08 UTC, Q3Neo commented
Mi sembra un regolamento ben fatto, tutti i punti a cui avevo pensato sono già presenti all'interno del documento.

2024-04-18 07:39 UTC, closed without merging